services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: npm start
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    restart: always
    ports:
      - "${FRONTEND_PORT:-8888}:8888"
