services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: npm start
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "${API_PORT:-3000}:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: sh -c "ls -la dist && http-server ./dist -p 8888 --cors -a 0.0.0.0 -P http://backend:3000/api -S -C /app/dist/index.html"
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "${FRONTEND_PORT:-8888}:8888"
