version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: npm start
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    command: npm run preview
    environment:
      - NODE_ENV=production
    restart: always
